apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
  namespace: application
  
spec:
  replicas: 2
  revisionHistoryLimit: 4
  template:
    spec:
      containers:
        - name: webapp
          image: "rpchan44/webapp:v1.0-dev"
