apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: configmap
    namespace: application
    literals:
      - version=rpchan44/webapp:v1.0-dev:main-667562f6847b8cfd7cdd031e6461f9a1d07d5ba3
    behavior: replace
    envs:
      - config.properties 

namePrefix: dev-

resources:
- ../../bases

patches:
- path: apps.yaml
