apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: configmap
    namespace: application
    literals:
      - version=rpchan44/webapp:v1.0-dev:main-40a6995ee8f0bc1affc8bf2972ab82a899791715
    behavior: replace
    envs:
      - config.properties 

namePrefix: dev-

resources:
- ../../bases

patches:
- path: apps.yaml
