apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: configmap
    namespace: application
    literals:
      - version=rpchan44/webapp:v1.0-dev:main-bc3696ca1f8267860d0893fb3e3f347801a34aa4
    behavior: replace
    envs:
      - config.properties 

namePrefix: dev-

resources:
- ../../bases

patches:
- path: apps.yaml
