apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

configMapGenerator:
- name: configmap
  behavior: replace
  envs:
  - config.properties

resources:
- ../../bases

patches:
- path: replicas.yaml
