apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: configmap
    namespace: application
    literals:
      - version=v1.0.1-dev
    behavior: replace
    envs:
      - config.properties 

namePrefix: dev-

resources:
- ../../bases

patches:
- path: replicas.yaml
