apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: configmap
    namespace: application
    literals:
      - version=rpchan44/webapp:v1.0-dev:main-0be8ad795a9cb0acc78d26502fec8c5a682215b1
    behavior: replace
    envs:
      - config.properties 

namePrefix: dev-

resources:
- ../../bases

patches:
- path: apps.yaml
