apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
  namespace: application
  
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: webapp-development
          image: "rpchan44/webapp:v1.0"
