apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machx-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rpchan44/learn-kustomize.git
    targetRevision: HEAD
    path: bases
  destination:
    server: https://kubernetes.default.svc
    namespace: application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
