apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

configMapGenerator:
- envs:
  - config.properties
  name: configmap
  
resources:
- ../../bases

patches:
- path: replicas.yaml
