apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

configMapGenerator:
  - name: configmap  # Name of the generated ConfigMap
    envs:
      - config.properties 

resources:
- ../../bases

patches:
- path: replicas.yaml
