apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: configmap
    behavior: replace
    envs:
      - config.properties 
      
namePrefix: prod-

resources:
- ../../bases

patches:
- path: replicas.yaml
