apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: configmap
    namespace: application
    literals:
      - version=v1.0.0-prod
    behavior: replace
    envs:
      - config.properties 
      
namePrefix: prod-

resources:
- ../../bases

patches:
- path: apps.yaml
