apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
  namespace: application
  
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: webapp-production
          image: "rpchan44/webapp:v1.0-prod"
