apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: development
patches:
- replicas.yaml

configMapGenerator:
- name: mykustom-map
  env: config.properties
