
resources: 
- deployment.yaml
- service.yaml

commonLabels:
  app: basic-app

commonAnnotations:
  app: basic-app-annontations

namePrefix:
  devel-

nameSuffix:
  -v1

configMapGenerator:
- name: mykustom-map
  env: config.properties
