apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-trunk
  namespace: trunk
spec:
  replicas: 5
  template:
    spec: # Pod spec
      containers:
      - name: webapp
        image: "devopsjourney1/mywebapp:latest"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: configmap
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
