apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
  namespace: application
spec:
  replicas: 2
  template:
    spec: # Pod spec
      containers:
      - name: webapp
        image: "rpchan44/webapp:v1.0"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: configmap
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
