apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app: backoffice-app

commonAnnotations:
  app: backoffice-app-annotations

namePrefix: machx-

nameSuffix: -v1

configMapGenerator:
- envs:
  - config.properties
  name: configmap

  
